Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'test/spec_helper.rb'
    - 'spec/factories/*'
    - 'vendor/**/*'
    - 'lib/tasks/display-coverage.rake'
    - 'loc_marc2bibframe2/**/*'

Lint/HandleExceptions:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/BlockLength:
  Max: 70

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 27

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
