language: ruby
sudo: false
rvm:
  - 2.6.3
cache:
  - bundler
  - directories
    - '/home/travis/.rvm/'
bundler_args: --without production
before_script:
  - mkdir -p tmp/Dataload/EndowRpt
  - mkdir -p tmp/Dataload/BookplateMerge/Batches/Queue
  - mkdir -p tmp/Dataload/UserloadRerun
  - mkdir -p tmp/Dataload/ILLiadUserExport
  - sudo mkdir -p /symphony/Libsys_webforms/sal3_batch_requests_batch/bc_file
  - sudo chmod -R a+w /symphony
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
  - bundle exec rake spec
